Repository elite37oficial/VAGAS_FLUTTER_BACKEND, pull requests merged in 2023-03, with the labels that each got.

#11 adicionadas dependencias ao projeto
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#12 criação de servidor customizado
  bin/custom_server.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement

#14 13 remoção das informações sensiveis
  .env
  bin/vagas_flutter_backend.dart
Labels: enhancement

#16 [feat]: criação das primeiras rotas e adição do middleware logRequest
  bin/vagas_flutter_backend.dart
Labels: enhancement

#17 7 rota login
  .gitignore
  atas.md
  bin/controllers/login_controller.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement

#18 3 rota listar vagas
  bin/controllers/jobs_controller.dart
  bin/vagas_flutter_backend.dart
  lib/vagas_flutter_backend.dart
  test/vagas_flutter_backend_test.dart
Labels: enhancement

#20 19 adição de middlewares
  bin/controllers/jobs_controller.dart
  bin/controllers/login_controller.dart
  bin/core/middlewares/middleware_interception.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement

#24 23 criação do modelo de jobs
  bin/models/job_model.dart
Labels: enhancement

#26 [feat]: criação do contrato de serviço que manipula dados
  bin/services/generic_service.dart
Labels: enhancement

#28 27 implementação do contrato de serviço genérico
  bin/controllers/jobs_controller.dart
  bin/models/job_model.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
  bin/utils/list_extension.dart
  bin/vagas_flutter_backend.dart
  ex.json
Labels: enhancement, Sprint I, feature

#30 [update]: atualiza gitignore
  .gitignore
  atas.md
Labels: documentation

#38 35 criação da camada dao
  bin/controllers/jobs_controller.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/models/job_model.dart
  bin/vagas_flutter_backend.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Sprint II, feature

#40 39 refatoração da camada services
  bin/controllers/jobs_controller.dart
  bin/models/job_model.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
  bin/vagas_flutter_backend.dart
Labels: Sprint II, refact

#42 41 criação do container de injeção de dependência
  bin/core/dependency_injector/dependency_injector.dart
  bin/core/dependency_injector/injects.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement, Sprint II, feature

#43 41 criação do container de injeção de dependência
  bin/controllers/jobs_controller.dart
  bin/controllers/ping_controller.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/models/job_details.dart
  bin/models/job_model.dart
  bin/models/job_simple.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
Labels: enhancement, Sprint II, feature

#48 45 criação e implementação do contrato jwt
  bin/controllers/login_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service.dart
  bin/core/security/security_service_imp.dart
Labels: enhancement, Sprint II, feature

#51 50 criação do contrato de controller
  bin/controllers/controller.dart
  bin/controllers/jobs_controller.dart
  bin/controllers/jobs_user_controller.dart
  bin/controllers/login_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/dao/jobs_dao.dart
  bin/services/jobs_service.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement, Sprint II, feature

#52 Refect Filtros de Vagas
  bin/controllers/jobs_controller.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/models/job_details.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
Labels: Sprint II, refact

#54 exclusão do model de admin e criação do model user
  bin/models/admin_model.dart
  bin/models/user_model.dart
Labels: Sprint II, refact

#55 53 criação de hash para senha
  bin/core/security/security_service_imp.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Sprint II, feature

#58 56 implementação de feature de login
  bin/controllers/jobs_security_controller.dart
  bin/controllers/jobs_user_controller.dart
  bin/controllers/login_controller.dart
  bin/controllers/ping_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service.dart
  bin/core/security/security_service_imp.dart
  bin/dao/jobs_dao.dart
  bin/dao/users_dao.dart
  bin/models/job_details.dart
  bin/models/job_model.dart
  bin/models/user_model.dart
  bin/services/auth_service.dart
  bin/services/users_service.dart
  bin/to/auth_to.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement, Sprint II, feature

#59 adicionando o campo estado no model de Jobs
  bin/dao/jobs_dao.dart
  bin/models/job_details.dart
  bin/models/job_model.dart
Labels: Sprint II, feature

#64 57 implementação da feature companies
  bin/controllers/companies_security_controller.dart
  bin/controllers/jobs_controller.dart
  bin/controllers/jobs_security_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/dao/companies_dao.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/dao/users_dao.dart
  bin/models/company_model.dart
  bin/models/job_details.dart
  bin/models/job_model.dart
  bin/services/companies_service.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
  bin/to/status_to.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement, feature, Sprint lll

#66 Criação de novas Rotas
  bin/controllers/users_security_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/dao/users_dao.dart
  bin/services/users_service.dart
  bin/vagas_flutter_backend.dart
Labels: feature, Sprint lll
