Repository elite37oficial/VAGAS_FLUTTER_BACKEND, pull requests merged in 2023-04, with the labels that each got.

#68 Refact/permissions
  bin/controllers/companies_security_controller.dart
  bin/controllers/jobs_security_controller.dart
  bin/controllers/login_controller.dart
  bin/controllers/users_security_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/dao/companies_dao.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/dao/users_dao.dart
  bin/models/job_model.dart
  bin/models/user_model.dart
  bin/services/companies_service.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
  bin/services/permissions_service.dart
  bin/services/users_service.dart
Labels: refact, Sprint lll

#72 Refact/global security
  bin/controllers/companies_security_controller.dart
  bin/core/security/security_service_imp.dart
  bin/dao/companies_dao.dart
  bin/dao/users_dao.dart
  bin/vagas_flutter_backend.dart
Labels: refact, Sprint lll

#74 73 denunciar vagas
  bin/controllers/jobs_report_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/dao/jobs_report_dao.dart
  bin/models/jobs_report_model.dart
  bin/services/jobs_report_service.dart
  bin/vagas_flutter_backend.dart
Labels: enhancement, feature, Sprint lll

#76 75 upload de imagem base 64
  bin/controllers/companies_images_controller.dart
  bin/controllers/companies_security_controller.dart
  bin/controllers/controller.dart
  bin/controllers/jobs_controller.dart
  bin/controllers/jobs_report_controller.dart
  bin/controllers/jobs_security_controller.dart
  bin/controllers/login_controller.dart
  bin/controllers/users_controller.dart
  bin/controllers/users_security_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/vagas_flutter_backend.dart
Labels: feature, refact, Sprint lll

#78 77 atualizar documentação
  bin/controllers/companies_images_controller.dart
  bin/core/middlewares/middleware_interception.dart
  bin/core/security/security_service_imp.dart
  bin/dao/jobs_dao.dart
  bin/models/job_details.dart
  bin/models/job_simple.dart
  bin/vagas_flutter_backend.dart
  pubspec.lock
  pubspec.yaml
  specs/swagger.yaml
Labels: documentation, enhancement, feature, refact, Sprint lll

#79 reset de senha via email
  bin/controllers/reset_passwords_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/dao/reset_passwords_dao.dart
  bin/dao/users_dao.dart
  bin/models/reset_password_model.dart
  bin/models/user_model.dart
  bin/services/reset_passwords_service.dart
  bin/vagas_flutter_backend.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, refact, Sprint lll

#80 Refatorando Informações
  bin/controllers/reset_passwords_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/dao/companies_dao.dart
  bin/models/company_model.dart
  bin/models/user_model.dart
  specs/swagger.yaml
Labels: refact

#81 reset de senha
  bin/controllers/reset_passwords_controller.dart
  bin/core/dependency_injector/injects.dart
  bin/core/security/security_service_imp.dart
  bin/dao/reset_passwords_dao.dart
  bin/models/reset_password_model.dart
  bin/services/reset_passwords_service.dart
Labels: feature, refact, Sprint lll

#83 Refact/change status
  bin/controllers/companies_security_controller.dart
  bin/controllers/jobs_security_controller.dart
  bin/controllers/ping_controller.dart
  bin/core/security/security_service_imp.dart
  bin/dao/companies_dao.dart
  bin/dao/dao.dart
  bin/dao/jobs_dao.dart
  bin/dao/users_dao.dart
  bin/models/company_model.dart
  bin/models/job_details.dart
  bin/models/job_model.dart
  bin/services/companies_service.dart
  bin/services/generic_service.dart
  bin/services/jobs_service.dart
  bin/to/status_to.dart
  specs/swagger.yaml
Labels: documentation, feature, refact, Sprint lll

#87 86 endpoint companyid
  bin/controllers/companies_security_controller.dart
  bin/core/security/security_service_imp.dart
  bin/models/company_model.dart
  specs/swagger.yaml
Labels: documentation, enhancement, feature, Sprint IV

#90 89 adicionar paginação para vagas
  bin/controllers/jobs_controller.dart
  bin/dao/jobs_dao.dart
  bin/models/job_simple.dart
  specs/swagger.yaml
Labels: documentation, feature, refact, Sprint IV
